### ISSUE TITLE
Adicionar suporte a tela cheia

### ISSUE THREAD

**Issue by laura-am06** [Erklan/jogo-web#18]
Adicionar um botão ou tecla de atalho para ativar ou desativar a tela cheia para o jogo.

**Comment by laura-am06** [comment]
Adicionei a spritesheet para fullscreen. Tentei configurar mas está dando erro, quando boto a configuração de suporte no index.js o arquivos não são mais lidos mais lidos e só aparece uma tela preta.

**Comment by boidacarapreta** [comment]
A versão do Phaser deve ser, preferencialmente, a última. No arquivo `index.html`, mudar da versão 3.11.0 para 3.24.1 (última estável:

```html
<script src="//cdn.jsdelivr.net/npm/phaser@3.24.1/dist/phaser.js"></script>
```

Além disso, adicionar na configuração do Phaser (arquivo `index.js`, bloco `var config`):

```js
scale: {
  mode: Phaser.Scale.FIT,
  parent: "game",
  autoCenter: Phaser.Scale.CENTER_BOTH,
  width: 900,
  height: 600,
},
```

ficando assim:

```js
var config = {
  type: Phaser.AUTO,
  width: 900,
  height: 600,
  parent: "game-container",
  physics: {
    default: "arcade",
    arcade: {
      gravity: { y: 300 },
      debug: false,
    },
  },
  scale: {
    mode: Phaser.Scale.FIT,
    parent: "game",
    autoCenter: Phaser.Scale.CENTER_BOTH,
    width: 900,
    height: 600,
  },
  scene: [cena0, cena1],
};
```

Testei há pouco com essas modificações e funcionou o suporte a tela cheia. Se quiser, toda a modificação para tela cheia, pelo menos para mim, está em: [https://github.com/boidacarapreta/arc20202/commit/4b192e3d11d1fc011fd06e9a2b44e34b97749d45](https://github.com/boidacarapreta/arc20202/commit/4b192e3d11d1fc011fd06e9a2b44e34b97749d45).

**Comment by laura-am06** [comment]
Obrigada, agora está funcionando, eu havia botado essas configurações no index antes, mas deixava a tela preta, talvez tenha sido por causa da versão.
